// <auto-generated />
using System;
using BigBooks.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigBooks.API.Migrations
{
    [DbContext(typeof(BigBookDbContext))]
    [Migration("20251119144801_AccountTransactionRestructure")]
    partial class AccountTransactionRestructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("BigBooks.API.Entities.AccountTransaction", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PurchaseQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionConfirmation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("BookKey");

                    b.HasIndex("UserKey");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Key = 1,
                            BookKey = 1,
                            PurchaseQuantity = 1,
                            TransactionAmount = -17.23m,
                            TransactionConfirmation = new Guid("962b4f1a-7520-4392-bfa7-11bea52517e8"),
                            TransactionDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserKey = 4
                        },
                        new
                        {
                            Key = 2,
                            TransactionAmount = 50.00m,
                            TransactionConfirmation = new Guid("db9b9784-ca26-4869-9a84-af2de7886f00"),
                            TransactionDate = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserKey = 4
                        },
                        new
                        {
                            Key = 3,
                            BookKey = 3,
                            PurchaseQuantity = 1,
                            TransactionAmount = -13.91m,
                            TransactionConfirmation = new Guid("962b4f1a-7520-4392-bfa7-11bea52517e8"),
                            TransactionDate = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserKey = 4
                        },
                        new
                        {
                            Key = 4,
                            BookKey = 2,
                            PurchaseQuantity = 3,
                            TransactionAmount = -33.21m,
                            TransactionConfirmation = new Guid("491adfcb-d596-4b46-8d6c-c395e8ec3611"),
                            TransactionDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserKey = 5
                        },
                        new
                        {
                            Key = 5,
                            BookKey = 8,
                            PurchaseQuantity = 2,
                            TransactionAmount = -16.71m,
                            TransactionConfirmation = new Guid("10a61e73-fada-472a-9589-3d784d190264"),
                            TransactionDate = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserKey = 5
                        },
                        new
                        {
                            Key = 6,
                            BookKey = 9,
                            PurchaseQuantity = 1,
                            TransactionAmount = -9.07m,
                            TransactionConfirmation = new Guid("3a3532de-cdb2-47b5-add3-209b4ba0991e"),
                            TransactionDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserKey = 5
                        },
                        new
                        {
                            Key = 7,
                            BookKey = 9,
                            PurchaseQuantity = 1,
                            TransactionAmount = -9.17m,
                            TransactionConfirmation = new Guid("69e93a9d-9d39-49fc-967a-4f0a3916a0ba"),
                            TransactionDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserKey = 5
                        },
                        new
                        {
                            Key = 8,
                            TransactionAmount = 75.00m,
                            TransactionConfirmation = new Guid("1a6b39cb-131a-4b34-aa98-1c3e00327302"),
                            TransactionDate = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserKey = 5
                        });
                });

            modelBuilder.Entity("BigBooks.API.Entities.AppUser", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Wallet")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Key = 1,
                            Password = "N0tV3ryS3cret",
                            Role = -1,
                            UserEmail = "Clark.Kent@demo.com",
                            UserName = "Clark Kent",
                            Wallet = 1m
                        },
                        new
                        {
                            Key = 2,
                            Password = "N0tV3ryS3cret",
                            Role = -1,
                            UserEmail = "Bruce.Wayne@demo.com",
                            UserName = "Bruce Wayne",
                            Wallet = 1m
                        },
                        new
                        {
                            Key = 3,
                            Password = "N0tV3ryS3cret",
                            Role = 0,
                            UserEmail = "Diana.Prince@demo.com",
                            UserName = "Diana Prince",
                            Wallet = 16.50m
                        },
                        new
                        {
                            Key = 4,
                            Password = "N0tV3ryS3cret",
                            Role = 0,
                            UserEmail = "Arthur.Anderson@demo.com",
                            UserName = "Arthur Anderson",
                            Wallet = 100.0m
                        },
                        new
                        {
                            Key = 5,
                            Password = "N0tV3ryS3cret",
                            Role = 0,
                            UserEmail = "Bella.Barnes@demo.com",
                            UserName = "Bella Barnes",
                            Wallet = 50.0m
                        },
                        new
                        {
                            Key = 6,
                            Password = "N0tV3ryS3cret",
                            Role = 0,
                            UserEmail = "Celeste.Cadwell@demo.com",
                            UserName = "Celeste Cadwell",
                            Wallet = 20.0m
                        });
                });

            modelBuilder.Entity("BigBooks.API.Entities.Book", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Key = 1,
                            Author = "Jon Scieszka",
                            Description = "A long time ago, people used to tell magical stories of wonder and enchantment. Those stories were called Fairy Tales.",
                            Genre = 2,
                            Isbn = new Guid("383ebbb6-8d11-4a7e-8411-07a2994bd3b1"),
                            Price = 17.51m,
                            StockQuantity = 23,
                            Title = "The Stinky Cheese Man and Other Fairly Stupid Tales"
                        },
                        new
                        {
                            Key = 2,
                            Author = "Maurice Sendak",
                            Description = "Let the wild rumpus continue as this classic comes to life like never before with new reproductions of Maurice Sendak's artwork.",
                            Genre = 2,
                            Isbn = new Guid("31ab208d-ea2d-458b-b708-744e16bbde5a"),
                            Price = 11.42m,
                            StockQuantity = 17,
                            Title = "Where the Wild Things Are"
                        },
                        new
                        {
                            Key = 3,
                            Author = "Sandy Asher",
                            Description = "Rabbit lives alone. He cooks for himself, cleans up for himself, and at the end of the day, reads himself a story. It's a simple life, and he likes it.",
                            Genre = 2,
                            Isbn = new Guid("623beb0c-3798-4629-9a4e-1894112b1122"),
                            Price = 13.70m,
                            StockQuantity = 45,
                            Title = "Too Many Frogs"
                        },
                        new
                        {
                            Key = 4,
                            Author = "Stephen Ambrose",
                            Description = "Citizen Soldiers opens at 0001 hours, June 7, 1944, on the Normandy beaches, and ends at 0245 hours, May 7, 1945, with the allied victory.",
                            Genre = 5,
                            Isbn = new Guid("d454af8a-fe4a-45ac-8fab-c220677ea6ed"),
                            Price = 17.11m,
                            StockQuantity = 6,
                            Title = "Citizen Soldiers"
                        },
                        new
                        {
                            Key = 5,
                            Author = "Brandon Sanderson",
                            Description = "It has been centuries since the fall of the 10 consecrated orders known as the Knights Radiant, but their Shardblades and Shardplate remain: mystical swords and suits of armor that transform ordinary men into near-invincible warriors. Men trade kingdoms for Shardblades. Wars were fought for them and won by them.",
                            Genre = 3,
                            Isbn = new Guid("c0cad277-f103-4c93-8a15-513fdfef2d5f"),
                            Price = 21.09m,
                            StockQuantity = 21,
                            Title = "The Way of Kings"
                        },
                        new
                        {
                            Key = 6,
                            Author = "Amor Towles",
                            Description = "In 1922, Count Alexander Rostov is deemed an unrepentant aristocrat by a Bolshevik tribunal, and is sentenced to house arrest in the Metropol, a grand hotel across the street from the Kremlin. Rostov, an indomitable man of erudition and wit, has never worked a day in his life, and must now live in an attic room.",
                            Genre = 1,
                            Isbn = new Guid("ff347fe2-9b34-41e5-ad04-afbd9cd2b568"),
                            Price = 11.19m,
                            StockQuantity = 17,
                            Title = "A Gentleman in Moscow"
                        },
                        new
                        {
                            Key = 7,
                            Author = "Some Guy",
                            Genre = 1,
                            Isbn = new Guid("230eca9f-474e-45d4-a412-977733cd8893"),
                            Price = 13.19m,
                            StockQuantity = 11,
                            Title = "My Story in BIG LETTERS"
                        },
                        new
                        {
                            Key = 8,
                            Author = "Suzanne Collins",
                            Description = "When Gregor falls through a grate in the laundry room of his apartment building, he hurtles into the dark Underland, where spiders, rats, cockroaches coexist uneasily with humans. This world is on the brink of war, and Gregor's arrival is no accident. ",
                            Genre = 2,
                            Isbn = new Guid("9909d495-cffb-4cf1-b876-cbb9857323d2"),
                            Price = 8.29m,
                            StockQuantity = 21,
                            Title = "Gregor the Overlander"
                        },
                        new
                        {
                            Key = 9,
                            Author = "Suzanne Collins",
                            Description = "Months have passed since Gregor first fell into the strange Underland beneath New York City, and he swears he will never go back. But he is destined to be a key player in another prophecy, this one about an ominous white rat called the Bane.",
                            Genre = 2,
                            Isbn = new Guid("09c64a27-f96c-4e3b-8361-dc3c2c8ada7a"),
                            Price = 9.46m,
                            StockQuantity = 13,
                            Title = "Gregor and the Prophecy of Bane"
                        },
                        new
                        {
                            Key = 10,
                            Author = "Suzanne Collins",
                            Description = "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.",
                            Genre = 3,
                            Isbn = new Guid("5672c761-c89d-460a-8877-ded4b48525f5"),
                            Price = 13.19m,
                            StockQuantity = 11,
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Key = 11,
                            Author = "Karin Slaughter",
                            Description = "In the city of Atlanta, young women are dying—at the hands of a killer who signs his work with a single, chilling act of mutilation. Leaving behind enough evidence to fuel a frenzied police hunt, this cunning madman is bringing together dozens of lives, crossing the boundaries of wealth and race.",
                            Genre = 3,
                            Isbn = new Guid("4929c5a8-8f0c-4f1a-a742-154f037c0761"),
                            Price = 19.23m,
                            StockQuantity = 3,
                            Title = "Triptych: A Will Trent"
                        });
                });

            modelBuilder.Entity("BigBooks.API.Entities.BookReview", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("BookKey");

                    b.HasIndex("UserKey");

                    b.ToTable("BookReviews");

                    b.HasData(
                        new
                        {
                            Key = 1,
                            BookKey = 1,
                            ReviewDate = new DateTime(2023, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 6,
                            UserKey = 4
                        },
                        new
                        {
                            Key = 2,
                            BookKey = 1,
                            Description = "My kids loved this book. I read it to them every night!",
                            ReviewDate = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 9,
                            UserKey = 5
                        },
                        new
                        {
                            Key = 3,
                            BookKey = 3,
                            ReviewDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 9
                        },
                        new
                        {
                            Key = 4,
                            BookKey = 3,
                            Description = "The plot wandered.",
                            ReviewDate = new DateTime(2025, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 6
                        },
                        new
                        {
                            Key = 5,
                            BookKey = 4,
                            ReviewDate = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 8
                        },
                        new
                        {
                            Key = 6,
                            BookKey = 5,
                            ReviewDate = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 9
                        },
                        new
                        {
                            Key = 7,
                            BookKey = 6,
                            ReviewDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 8
                        },
                        new
                        {
                            Key = 8,
                            BookKey = 6,
                            ReviewDate = new DateTime(2024, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 7
                        },
                        new
                        {
                            Key = 9,
                            BookKey = 7,
                            ReviewDate = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 7
                        },
                        new
                        {
                            Key = 10,
                            BookKey = 7,
                            ReviewDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 8
                        },
                        new
                        {
                            Key = 11,
                            BookKey = 9,
                            Description = "This book was way too dark for kids.",
                            ReviewDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 3,
                            UserKey = 5
                        },
                        new
                        {
                            Key = 12,
                            BookKey = 9,
                            Description = "Every child should read this book.",
                            ReviewDate = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 10,
                            UserKey = 2
                        },
                        new
                        {
                            Key = 13,
                            BookKey = 7,
                            Description = "This book was long and boring.",
                            ReviewDate = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 5,
                            UserKey = 5
                        });
                });

            modelBuilder.Entity("BigBooks.API.Entities.AccountTransaction", b =>
                {
                    b.HasOne("BigBooks.API.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookKey");

                    b.HasOne("BigBooks.API.Entities.AppUser", "AppUser")
                        .WithMany("Transactions")
                        .HasForeignKey("UserKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BigBooks.API.Entities.BookReview", b =>
                {
                    b.HasOne("BigBooks.API.Entities.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BigBooks.API.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserKey");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BigBooks.API.Entities.AppUser", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BigBooks.API.Entities.Book", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
